% Overall Purpose
% This script takes:

% 1. The original lung MRI frames (the same ones we used for the manual ROI method).

% 2. The automated lung segmentation masks generated by nnU‑Net (from my prediction runs).

% 3. It then computes the average pixel intensity inside the lung region for every time frame,
% producing a respiratory waveform that reflects breathing motion.

% This is essentially what the automated intensity‑based method does, i.e. it selects the ROI automatically.

% Batch version: looping through all patients and slices.

close all;
clearvars;
tic; % Start the timer

%% Setting base directories

% Defining the root folder where patient data are stored
patientDataRoot = 'C:\Users\makan\Downloads\ben_mina\Patient Data';

% Defining the root folder where nnU‑Net segmentation masks are saved
maskRoot = 'C:\Users\makan\Downloads\ben_mina\masks';

% Defining the base folder where the extracted waveforms will be saved (for the ML method)
outputBase = 'C:\Users\makan\Downloads\ben_mina\MATLAB Respiratory Waveform\Waveform Outputs\ML';

% Adding current folder to path (for natsortfiles if needed)

% This ensures that any custom functions (like natsortfiles) in the current directory or subfolders are accessible
addpath(genpath(pwd));

%% Asking for global auto-accept mode, so that I can run without needing to confirm every single thing

globalAuto = false;
reply = input('Run in global auto-accept mode? (y/n): ', 's');
if strcmpi(reply, 'y')
    globalAuto = true;
    fprintf('Global auto-accept mode ON so no prompts (or figures).\n');
else
    fprintf('Manual mode – you will be prompted per slice.\n');
end
%% Outer Loop - I'm Looping through all patients 

% Getting list of patient folders
% Scanning the patient data root for folders that start with 'HV_'
patientFolders = dir(fullfile(patientDataRoot, 'HV_*')); % adjust pattern if needed, but so far thats the syntax I have

% Filtering the list to keep only directories (excluding files)
patientFolders = patientFolders([patientFolders.isdir]);

% Initialise table for normalisation check
normCheckAuto = table();

% This is essentially a nested for loop, I am looping through my patients and my slices so that I don't repeat everything per slice

for p = 1:length(patientFolders)
    patientName = patientFolders(p).name;
    patientPath = fullfile(patientDataRoot, patientName);

    % Constructing the corresponding path to the masks for this patient
    maskPatientPath = fullfile(maskRoot, patientName);

    % Getting list of slice folders for this patient
    % Looking inside the patient folder for subfolders that start with 'raw_IM_'
    sliceFolders = dir(fullfile(patientPath, 'raw_IM_*')); % adjust pattern if needed, but so far thats the syntax I have

    % Keeping only directories
    sliceFolders = sliceFolders([sliceFolders.isdir]);

%% Inner loop, so im looping per slice, then loading frames and masks

% In this loop I load the frames, apply the masks and compute the signals

    for s = 1:length(sliceFolders)
        sliceName = sliceFolders(s).name;
        % Full path to the original frames for this slice
        origPath = fullfile(patientPath, sliceName);
        % Full path to the corresponding masks for this slice
        maskPath = fullfile(maskPatientPath, sliceName);

        fprintf('\nProcessing %s / %s\n', patientName, sliceName);

        % Getting sorted lists of frame and mask files
        % Using natsortfiles to ensure natural numerical order (e.g., frame 1,2,...10 not 1,10,2)
        origFiles = natsortfiles(dir(fullfile(origPath, '*.nii*')));
        maskFiles = natsortfiles(dir(fullfile(maskPath, '*.nii*')));

        % Checking if either frames or masks are missing; if so, skip this slice
        if isempty(origFiles) || isempty(maskFiles)
            warning('Missing frames or masks in %s / %s, skipping.', patientName, sliceName);
            continue;
        end

        % Determining the number of frames to process (using the smaller count in case they differ)
        numFrames = min(numel(origFiles), numel(maskFiles));

        % Reading first frame to get dimensions
        tmp = read_nii_gz(fullfile(origPath, origFiles(1).name));
        tmp = squeeze(double(tmp));
        dimx = size(tmp, 1);
        dimy = size(tmp, 2);

        % Loading frames and masks
        Proton = zeros(dimx, dimy, numFrames); % just pre allocating here
        MaskAll = false(dimx, dimy, numFrames); % pre‑allocating a logical array for masks
        for k = 1:numFrames
            % Loading and storing each original frame
            I = read_nii_gz(fullfile(origPath, origFiles(k).name));
            I = squeeze(double(I));
            Proton(:,:,k) = I;

            % Loading and storing each mask, converting to logical (true where lung is present)
            M = read_nii_gz(fullfile(maskPath, maskFiles(k).name));
            M = squeeze(double(M));
            MaskAll(:,:,k) = M > 0;
        end

        % Capturing the global maximum before normalisation
        preMax = max(Proton(:));
        fprintf('  For %s / %s, maximum value before normalisation is %f\n', patientName, sliceName, preMax);

        % Normalisation
        % Dividing every pixel in every frame by the single brightest pixel across all frames
        % This scales the entire stack to the range [0,1] (plus eps to avoid division by zero)
        Proton = Proton ./ max(Proton(:) + eps);

        postMax = max(Proton(:));
        fprintf('  For %s / %s, maximum value after normalisation is %f\n', patientName, sliceName, postMax);

        % Applying a minimum filter
        % Creating a new array for filtered images
        ProtonFilt = zeros(size(Proton));
        for k = 1:size(Proton, 3)
            temp = Proton(:,:,k);
            % Using a 3x3 minimum filter (ordfilt2 with order 1) to reduce blood vessel signals
            ProtonFilt(:,:,k) = ordfilt2(temp, 1, ones(3,3));
        end

        % Setting timing parameters
        % Total acquisition duration (in seconds), hard‑coded based on the
        % dataset, given by Ben
        AcqDur = 70.157;
        TA = AcqDur / numFrames; % time per frame (seconds)
        fs = 1 / TA;              % sampling frequency (Hz)

        if ~globalAuto

            %% Interactive loop for each slice (with overlay check and acceptance)
            while true

              % overlay check first  
                frameCheck = min(30, numFrames); % choosing a representative frame (30 or last)
                figure('Name', 'Mask Overlay Check');
                imshow(ProtonFilt(:,:,frameCheck), []); hold on;

                % Overlaying the mask contour on the filtered image in green
                contour(MaskAll(:,:,frameCheck), [1 1], 'g', 'LineWidth', 2);
                title(sprintf('Mask overlay check (frame %d)', frameCheck));
                drawnow();

                % Pausing and waiting for user to press Enter to continue
                input('Press Enter to continue...');
                close(gcf);

                Signal = zeros(1, numFrames);
                for k = 1:numFrames
                    frame = ProtonFilt(:,:,k);
                    mask  = MaskAll(:,:,k);
                    % Computing the mean intensity of the filtered image inside the lung mask
                    Signal(k) = mean(frame(mask));  % the signal is the mean of the pixel intensities inside the ROI/mask
                end

                time = (0:numFrames-1) * TA; % converting from frames to time so that we can see how the signal evolves over time
%% Creating and displaying figures

                figure('Color', 'white');
                plot(time, Signal, 'Color', [0.2 0.2 0.2], 'LineWidth', 2);
                xlabel('Time (s)');
                ylabel('Mean Intensity in Lung Mask');
                title('Respiratory Waveform (Automated Mask)');

                % Setting axes properties for a clean, presentation‑ready appearance
                set(gca, 'FontName', 'Arial', 'FontSize', 14, 'LineWidth', 2, ...
                         'YMinorTick', 'on', 'Box', 'off', 'Color', 'white', ...
                         'XColor', 'k', 'YColor', 'k');
                set(get(gca, 'Title'), 'Color', 'k', 'FontWeight', 'bold');
                set(get(gca, 'XLabel'), 'Color', 'k');
                set(get(gca, 'YLabel'), 'Color', 'k');
                grid on;
                drawnow();

                % Save the waveform figure as PNG
                waveformFigFile = fullfile(outputDir, 'automated_waveform.png');
                saveas(gcf, waveformFigFile);
                fprintf('  Waveform figure saved to %s\n', waveformFigFile);

                % Asking the user whether the waveform looks acceptable
                qualityc = input('Is the respiratory waveform okay? (y/n): ', 's');
                if strcmpi(qualityc, 'y')
                    break; % if accepted, exit the loop and proceed to saving
                else
                    close(gcf); % close the waveform figure and repeat the whole process for this slice
                    fprintf('Repeating extraction, you can inspect again.\n');
                end
            end
        else

            %% If I say yes to global auto, the else condition runs, no need to check any overlays, just computes everything in one go
            % Auto mode: computing waveform directly without interaction
            Signal = zeros(1, numFrames);
            for k = 1:numFrames
                frame = ProtonFilt(:,:,k);
                mask  = MaskAll(:,:,k);

                % Computing the mean intensity inside the mask for each frame
                Signal(k) = mean(frame(mask)); % the signal is the mean of the pixel intensities inside the ROI/mask

            end
            time = (0:numFrames-1) * TA; % converting from frames to time so that we can see how the signal evolves over time
            frameCheck = min(30, numFrames);  % for overlay (used later for saving the overlay image)

            % Save the waveform figure without displaying
            waveformFig = figure('Visible', 'off');
            plot(time, Signal, 'Color', [0.2 0.2 0.2], 'LineWidth', 2);
            xlabel('Time (s)');
            ylabel('Mean Intensity in Lung Mask');
            title(sprintf('Respiratory Waveform (Automated Mask) - %s / %s', patientName, sliceName));
            set(gca, 'FontName', 'Arial', 'FontSize', 14, 'LineWidth', 2, ...
                     'YMinorTick', 'on', 'Box', 'off', 'Color', 'white', ...
                     'XColor', 'k', 'YColor', 'k');
            set(get(gca, 'Title'), 'Color', 'k', 'FontWeight', 'bold');
            set(get(gca, 'XLabel'), 'Color', 'k');
            set(get(gca, 'YLabel'), 'Color', 'k');
            grid on;
            waveformFigFile = fullfile(outputDir, 'automated_waveform.png');
            saveas(waveformFig, waveformFigFile);
            close(waveformFig);
            fprintf('  Waveform figure saved to %s\n', waveformFigFile);
        end        
%% Saving overlayed image in this section
        % Saving mask overlay image (always, regardless of mode, so that I know what they looked like
        outputDir = fullfile(outputBase, patientName, sliceName);
        if ~exist(outputDir, 'dir')
            mkdir(outputDir); % creating the output folder if it doesn't exist
        end
        overlayFile = fullfile(outputDir, 'mask_overlay.png');
        
        % Creating an invisible figure to generate the overlay image without displaying it
        f = figure('Visible', 'off');
        imshow(ProtonFilt(:,:,frameCheck), []); hold on;
        contour(MaskAll(:,:,frameCheck), [1 1], 'g', 'LineWidth', 2);
        title(sprintf('Automated Mask on %s / %s (frame %d)', patientName, sliceName, frameCheck));
        saveas(f, overlayFile); % saving the figure as a PNG file
        close(f); % closing the invisible figure

        % Record normalisation check for this slice
        newRowNorm = table({patientName}, {sliceName}, preMax, postMax, ...
            'VariableNames',{'Patient','Slice','PreMax','PostMax'});
        normCheckAuto = [normCheckAuto; newRowNorm];

        % Saving waveform in structured folder
        % Storing the signal, time axis, and metadata in a .mat file
        save(fullfile(outputDir, 'automated_waveform.mat'), 'Signal', 'time', 'fs', 'TA', 'numFrames');
        fprintf('Waveform saved to %s\n', fullfile(outputDir, 'automated_waveform.mat'));
    end
end

% Save normalisation check table
normFile = fullfile(outputBase, 'normalisation_check_auto.csv');
writetable(normCheckAuto, normFile);
fprintf('Normalisation check saved to %s\n', normFile);

%% Helper function: reading a NIfTI file (supports both .nii and .nii.gz)
function V = read_nii_gz(fname)
    try
        % Attempting to read the file directly using MATLAB's niftiread
        V = niftiread(fname);
    catch
        % If direct reading fails and the file ends with .gz, unzip it first
        if endsWith(fname, ".gz")
            tmpDir = fullfile(tempdir, "prefu_tmp");
            if ~exist(tmpDir, "dir"); mkdir(tmpDir); end % creating temporary folder
            gunzip(fname, tmpDir); % unzipping the file into the temporary folder
            % Constructing the path to the unzipped file (removing .gz extension)
            unz = fullfile(tmpDir, erase(string(fname), ".gz"));
            V = niftiread(unz); % reading the unzipped file
            delete(unz); % deleting the temporary file to clean up
        else
            % If it's not a .gz file, rethrow the original error
            rethrow(lasterror);
        end
    end
end

elapsedTime = toc; % Read the elapsed time
fprintf('Elapsed time: %.2f seconds\n', elapsedTime);